spring.application.name=webforj-ai-chat-component
server.shutdown=immediate

webforj.entry=com.example.aichat.Application
webforj.debug=true
webforj.devtools.browser.open=false
webforj.devtools.livereload.enabled=true
